artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  # We will use a public mirror for the automation example.
  # If you have the file locally, you can put "local" here and logic in the component.
  source_URL: https://github.com/SebastianGarrido2790/Data-Science-Portfolio/raw/refs/heads/main/books.csv.zip 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/books.csv